import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../assets/images/logo-l2f.tech.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>L2F.Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.contentContainer}>
          <Image src={logo} className={styles.logoImage}/>
          <h2 className={styles.contentTitle}>Nosso site está em construção!</h2>
          <p className={styles.contentDescription}>Logo mais em breve, chegaremos para lhe oferecer mais comodidade e facilidade em seu dia a dia!</p>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
